name: Say hello to workflow requester

on:
  workflow_dispatch:
    inputs:
      greeting:
        description: Provide a special greeting
        type: string
        default: Hello

jobs:
  greet:
    name: Say hello
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo '${{ inputs.greeting }}, ${{ github.actor }}'
